name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: install shellspec
        run: curl -sfSL https://git.io/shellspec | sh -s 0.28.1 --yes
      - run: which shellspec
      - run: npm install
      - run: npm run standard
      - run: npm test
